config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :alerts
  
  # Goals routes
  resources :goals
  get 'goals/:id/new_sub_goal', to: 'goals#new_sub_goal', as: 'new_sub_goal'
  post 'goals/:id/create_sub_goal', to: 'goals#create_sub_goal', as: 'create_sub_goal'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/alert.rb
# == Schema Information
#
# Table name: alerts
#
#  id         :bigint           not null, primary key
#  title      :string
#  interval   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Alert < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :interval, presence: true
  has_many :goals
end

app/models/alert_type.rb
# == Schema Information
#
# Table name: alert_types
#
#  id         :bigint           not null, primary key
#  title      :string
#  interval   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class AlertType < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :interval, presence: true
  has_many :goals
end

app/controllers/alerts_controller.rb
# frozen_string_literal: true

class AlertsController < ApplicationController
  before_action :set_alert, only: %i[show edit update destroy]

  # GET /alerts or /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1 or /alerts/1.json
  def show; end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit; end

  # POST /alerts or /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to(alert_url(@alert), notice: 'Alert was successfully created.') }
        format.json { render(:show, status: :created, location: @alert) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @alert.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /alerts/1 or /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to(alert_url(@alert), notice: 'Alert was successfully updated.') }
        format.json { render(:show, status: :ok, location: @alert) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @alert.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /alerts/1 or /alerts/1.json
  def destroy
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to(alerts_url, notice: 'Alert was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_alert
    @alert = Alert.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def alert_params
    # params.fetch(:alert, {})
    params.require(:alert).permit(:title, :interval)
  end
end

app/helpers/alert_helper.rb
# frozen_string_literal: true

module AlertHelper
end

app/helpers/alerts_helper.rb
# frozen_string_literal: true

module AlertsHelper
end

app/views/alerts/_alert.html.slim
div id="#{dom_id alert}" class="mb-4"
	h2 class="uppercase tracking-wide text-sm text-indigo-600 font-bold" 
		= alert.title

app/views/alerts/_form.html.slim
= form_with(model: @alert) do |form|
  - if @alert.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@alert.errors.count, "error")} prohibited this alert from being saved:"
      ul
        - @alert.errors.each do |error|
          li = error.full_message

  .flex.flex-wrap.-mx3.mb-6
      .w-full.py-3
        = form.label :title, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.text_field :title, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      
      .w-full.py-3
        = form.label :interval, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.number_field :interval, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"

  div
      = render ButtonComponent.new(title: "Save Alert", type: "submit")
      / = form.submit
  

app/views/alerts/edit.html.slim
h1 Editing alert

== render "form", alert: @alert

br

div
  => link_to "Show this alert", @alert
  '|
  =< link_to "Back to alerts", alerts_path

app/views/alerts/index.html.slim
p style="color: green" = notice

h1.text-3xl.text-orange-500.text-center Alerts

#alerts
  - @alerts.each do |alert|
    .border-2.border-rose-600.mb-6.pb-6.flex.justify-around.items-center.w-full
      == render alert
      p
        = link_to "Show this alert", alert, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"

= link_to "New alert", new_alert_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"

app/views/alerts/new.html.slim
h1 New alert

== render "form", alert: @alert

br

div
  = link_to "Back to alerts", alerts_path

app/views/alerts/show.html.slim
p style="color: green" = notice

== render @alert

div
  => link_to "Edit this alert", edit_alert_path(@alert)
  '|
  =< link_to "Back to alerts", alerts_path

  = button_to "Destroy this alert", @alert, method: :delete