config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :alerts
  
  # Goals routes
  resources :goals
  get 'goals/:id/new_sub_goal', to: 'goals#new_sub_goal', as: 'new_sub_goal'
  post 'goals/:id/create_sub_goal', to: 'goals#create_sub_goal', as: 'create_sub_goal'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/goal.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: goals
#
#  id                      :bigint           not null, primary key
#  name                    :string
#  desc                    :string
#  start_at                :datetime
#  end_at                  :datetime
#  active                  :boolean          default(TRUE)
#  completed               :boolean          default(FALSE)
#  parent_id               :integer
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  alert_id                :integer
#  last_alert_generated_at :datetime
#
class Goal < ApplicationRecord
  validates :name, presence: true
  validates :start_at, presence: true
  has_many :goal_alerts, dependent: :destroy
  # belongs_to :alert_type
  belongs_to :alert
end

app/controllers/goals_controller.rb
# frozen_string_literal: true

class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update destroy]

  # GET /goals or /goals.json
  def index
    # @goals = Goal.where("user_id = ? and parent_id = ?", current_user.id, nil)
    @goals = Goal.where(user_id: current_user.id).where(parent_id: nil)
  end

  # GET /goals/1 or /goals/1.json
  def show
    @goal_alert = GoalAlert.where('goal_id = ?', params[:id])
    @sub_goals = Goal.where('parent_id = ?', params[:id])
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit; end

  # POST /goals or /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    respond_to do |format|
      if @goal.save
        @goal_alert = GoalAlert.new
        @goal_alert.goal_id = @goal.id
        @goal_alert.question = params.require(:goal).permit(:alert_question).values[0]
        @goal_alert.save
        format.html { redirect_to(goal_url(@goal), notice: 'Goal was successfully created.') }
        format.json { render(:show, status: :created, location: @goal) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @goal.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to(goal_url(@goal), notice: 'Goal was successfully updated.') }
        format.json { render(:show, status: :ok, location: @goal) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @goal.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to(goals_url, notice: 'Goal was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  def new_sub_goal
    @goal = Goal.new
    @parent_id = params[:id]
  end

  def create_sub_goal
    @goal = Goal.new(goal_params)
    @goal.parent_id = params[:id]
    respond_to do |format|
      if @goal.save
        @goal_alert = GoalAlert.new
        @goal_alert.goal_id = @goal.id
        @goal_alert.question = params.require(:goal).permit(:alert_question).values[0]
        @goal_alert.save
        format.html { redirect_to(goal_url(@goal), notice: 'Sub Goal was successfully created.') }
        format.json { render(:show, status: :created, location: @goal) }
      else
        format.html { redirect_to(new_sub_goal, notice: 'Error while submitting Form.', status: :unprocessable_entity) }
        format.json { render(json: @goal.errors, status: :unprocessable_entity) }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_goal
    @goal = Goal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def goal_params
    # params.fetch(:goal, {})
    params.require(:goal).permit(:name, :desc, :start_at, :end_at, :active, :completed, :alert_id)
  end
end

app/helpers/goal_helper.rb
# frozen_string_literal: true

module GoalHelper
end

app/helpers/goals_helper.rb
# frozen_string_literal: true

module GoalsHelper
end

app/views/goals/_form.html.slim
.w-full.max-w-lg
  = form_with(model: @goal) do |form|
    - if @goal.errors.any?
      div style="color: red"
        h2 = "#{pluralize(@goal.errors.count, "error")} prohibited this goal from being saved:"
        ul
          - @goal.errors.each do |error|
            li = error.full_message
    .flex.flex-wrap.-mx3.mb-6
      .w-full.py-3
        = form.label :name, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.text_field :name, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.py-3 
        = form.label :desc, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.text_area :desc, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.py-3 
        = form.label :start_at, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.date_field :start_at, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.py-3 
        = form.label :end_at, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.date_field :end_at, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.flex.items-center.py-3 
        = form.check_box :active, class: "mr-2 leading-tight"
        = form.label :active, class: "block text-gray-500 font-bold"
      .w-full.flex.items-center.py-3
        = form.check_box :completed, class: "mr-2 leading-tight"
        = form.label :completed, class: "block text-gray-500 font-bold"
      /.w-full.py-3 
      /  = form.label :alert_type, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
      /  = form.number_field :alert, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"

      .w-full.py-3 
        = form.label :alert_id, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.collection_select(:alert_id, Alert.all, :id, :title , {}, { multiple: false, size: 4, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight" })
        / = form.collection_select(:alert_type, Alert.all, :id, :title , {}, { multiple: true, size: 4, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight" })
        
      .w-full.py-3
        = form.label :alert_question, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.text_field :alert_question, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"

    div
      = render ButtonComponent.new(title: "Save Goal", type: "submit")
      / = form.submit



/ - if parent_id
/         div 
/           = form.submit 
/           / = link_to "Save Sub Goal", create_sub_goal_path(parent_id), data: { turbo_method: "post" } 
/           / = button_to 'Save sub goal', create_sub_goal_path(parent_id)
/           / = link_to "Save sub goal", create_sub_goal_path(parent_id), method: :post
/     - else 
/         div
/           = render ButtonComponent.new(title: "Save Goal", type: "submit")
/           / = form.submit

app/views/goals/_goal.html.slim
div id="#{dom_id goal}"

    =render CardComponent.new(goal:goal, alert: goal.alert.title)

app/views/goals/edit.html.slim
h1 Editing goal

== render "form", goal: @goal

br

div
  => link_to "Show this goal", @goal
  '|
  =< link_to "Back to goals", goals_path

app/views/goals/index.html.slim
p style="color: green" = notice

h1.text-xl.font-semibold Goals

#goals
  - @goals.each do |goal|
    == render goal

.flex.justify-center
  = link_to "New goal", new_goal_path, class: "py-3 px-8 bg-red-400 hover:bg-red-800"

app/views/goals/new.html.slim
.flex.flex-col.justify-center.items-center.w-full
  h1.text-xl.font-semibold.mb-4.text-gray-700 New goal

  == render "form", goal: @goal

  br

  div
    = link_to "Back to goals", goals_path

app/views/goals/new_sub_goal.html.slim
h1 Create new sub goal

/ == render "form", goal: @goal, parent_id: @parent_id

.w-full.max-w-lg
  = form_with(model: @goal, url: create_sub_goal_path(@parent_id)) do |form|
    - if @goal.errors.any?
      div style="color: red"
        h2 = "#{pluralize(@goal.errors.count, "error")} prohibited this goal from being saved:"
        ul
          - @goal.errors.each do |error|
            li = error.full_message
    .flex.flex-wrap.-mx3.mb-6
      .w-full.py-3
        = form.label :name, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.text_field :name, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.py-3 
        = form.label :desc, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.text_area :desc, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.py-3 
        = form.label :start_at, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.date_field :start_at, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.py-3 
        = form.label :end_at, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.date_field :end_at, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"
      .w-full.flex.items-center.py-3 
        = form.check_box :active, class: "mr-2 leading-tight"
        = form.label :active, class: "block text-gray-500 font-bold"
      .w-full.flex.items-center.py-3
        = form.check_box :completed, class: "mr-2 leading-tight"
        = form.label :completed, class: "block text-gray-500 font-bold"
      /.w-full.py-3 
      /  = form.label :alert_type, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
      /  = form.number_field :alert, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"

      .w-full.py-3 
        = form.label :alert_id, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.collection_select(:alert_id, Alert.all, :id, :title , {}, { multiple: false, size: 4, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight" })
        / = form.collection_select(:alert_type, Alert.all, :id, :title , {}, { multiple: true, size: 4, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight" })
        
      .w-full.py-3
        = form.label :alert_question, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
        = form.text_field :alert_question, class: "appearance-none block w-full rounded py-3 px-4 mb-3 leading-tight"

      = render ButtonComponent.new(title: "Save Sub Goal", type: "submit")

br

div
  => link_to "Show this goal", @goal
  '|
  =< link_to "Back to goals", goals_path

app/views/goals/show.html.slim
p style="color: green" = notice

== render @goal

.mt-4.mx-auto   
  h3.font-bold Goal Alert Question 

  - for alert in @goal_alert
    p =alert.question

.mt-4 
  h3.font-bold Sub Goals 
  - for sub_goal in @sub_goals
    h4 =sub_goal.name

.mt-4   
  = link_to "Create Sub Goal", new_sub_goal_path


div.mt-4
  => link_to "Edit this goal", edit_goal_path(@goal)
  '|
  => link_to "Back to goals", goals_path
  '|
  
  = button_to "Destroy this goal", @goal, method: :delete